### PR TITLE
Add BoostMode and FieldValueFactor score function

### PR DESCRIPTION
**Pull request by flavienaudin**
Hi,
Does this feature interest you? Is there other thing to do to validate the PR ?

### CODE REVIEW

**Comment by CheapHasz** [comment]
I personally am fine with these features (BoostMode and FieldValueFactor) once the BoostMode setter is corrected.

Sometimes we add tests when we deem it necessary, but the fact that tests are still passing (and the logic behind it) is enough for me to consider the features ok.

**Comment by flavienaudin** [comment]
> once the BoostMode setter is corrected.

You mean : added  `return this;` ?

I added a test for the FieldValueFactorScore.

**Comment by CheapHasz** [comment]
No. I mean that the TypeHint of the `setBoostMode` can not be an BoostMode object, as you will pass it something like `BoostMode::MULTIPLY`, which is a string

**Comment by flavienaudin** [comment]
Indeed! I also write a test

**Comment by CheapHasz** [comment]
Would you mind adding a verification in the setter, ensuring that the `$boostMode` is a valid one ? 

(pretty much like the 
```
if (!in_array($modifier, [self::NONE, self::LN, self::LN1P, self::LN2P, self::LOG, self::LOG1P, self::LOG2P, self::SQUARE, self::SQRT, self::RECIPROCAL])) {
            throw new \InvalidArgumentException(sprintf("function should be one of %s, %s, %s, %s, %s, %s, %s, %s, %s, %s : %s given", self::NONE, self::LN, self::LN1P, self::LN2P, self::LOG, self::LOG1P, self::LOG2P, self::SQUARE, self::SQRT, self::RECIPROCAL, $modifier));
        }
``` in the FieldValueFactorScore constructor) 

That way a typo wouldn't go unnoticed, or throw a cryptic error.

And you could use this setter in the `__construct` method, ensuring that the test is alwayd passed.

**Comment by CheapHasz** [comment]
Thanks

**Comment by flavienaudin** [comment]
Hi again,
Do you think this PR can be also merged in version >= 6 ?

Flavien

**Pull request merged**
