### PR TITLE
Dynamic geofilter distance unit

### LINKED ISSUE #26: Make distance unit a parameter in GeoDistanceFilter.php
GeoDistanceFilter.php currently has "km" as an hardcoded value for distance unit.

It would be useful to have a parameter.

### PR DESCRIPTION
**Pull request by CheapHasz**
Fixed #26 and added support for additional options

### CODE REVIEW

**Comment by jdecool** [comment]
👍 

LGTM

Wouldn't it be interesting to add an enum class for the distance units ?

**Comment by CheapHasz** [comment]
It would not hurt, but I feel it would kinda be overkill :  

There are a lot of units, most of them useless, and very unlikely to change.

And everything only for these geoqueries ...

**Comment by jdecool** [comment]
This was to take advantage of the IDE autocompletion and avoid having to look at the documentation for possible values.

It was just a suggestion :)

**Comment by skwi** [comment]
I aggree with @CheapHasz. Although the use of constants can be a usefull for DX, it's too unsteady to be listed exhaustively. 

This PR is good to me.

**Pull request merged**
