### PR TITLE
Add GeoDistance filter

### PR DESCRIPTION
**Pull request by delphiki**
Add integration of GeoDistance filter (only in 1.7 as it's been removed in further versions of ES).

### CODE REVIEW

**Comment by CheapHasz** [comment]
It seems that it has been replaced by the GeoDistance query in further versions, which seems to work pretty much the same way
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-geo-distance-query.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-geo-distance-query.html

**Comment by delphiki** [comment]
@CheapHasz Yep I saw, I just didn't have the motivation to write the corresponding query for v2.x :)

**Comment by delphiki** [comment]
Any update? :)

**Comment by jdecool** [comment]
A class was added but not used anywhere. Does it miss something ?
Maybe a small documentation ?

And some tests ?

**Comment by skwi** [comment]
Closing because of https://github.com/novaway/elasticsearch-client/pull/24

**Pull request closed without merging**
